### PR TITLE
Update protocol and generate SIP API

### PR DESCRIPTION
**Pull request by dennwc**

### CODE REVIEW

**Review by theomonnom — APPROVED** [review]
lgtm

**Comment by dennwc** [comment]
Hmm, looks like it won't work without properly updating the client. I planned to do a separate PR for it, but lets keep this one open until I fix it then.

**Comment by dennwc** [comment]
@theomonnom Could you take another look please? It's my first code in Rust, so might be sub-optimal :sweat_smile:

**Comment by dennwc** [comment]
I'm not exactly sure why the tests are failing now :thinking:

**Comment by theomonnom** [comment]
> I'm not exactly sure why the tests are failing now 🤔

Feel free to ignore, these tests are broken for now. Will review asap

**Review by theomonnom — APPROVED** [review]
nice🚀

**Pull request merged**
