### PR TITLE
add JNI_OnLoad on livekit_ffi

### PR DESCRIPTION
**Pull request by theomonnom**

### CODE REVIEW

**Comment by cloudwebrtc** [comment]
No more crashes, but need to put `libwebrtc.jar` with `liblivekit_ffi.so` into `unityLibrary`.

**Comment by theomonnom** [comment]
Ok nice, makes sense, I have one here: https://github.com/livekit/rust-sdks/blob/main/examples/mobile/android/app/libs/libwebrtc.jar

**Comment by theomonnom** [comment]
Feel free to approve so I can merge :)

**Comment by cloudwebrtc** [comment]
We may need to modify CI and package libwebrtc.jar together into ffi-android-${archs}.zip ?

**Pull request merged**
