### PR TITLE
add nanpa version management support

### PR DESCRIPTION
**Pull request by nbsp**
this adds support for versioning through [nanpa](https://github.com/nbsp/nanpa), via the [ilo](https://github.com/nbsp/ilo) GitHub bot.

## usage guide
1. on PRs, for each change, add a file to `.nanpa/<unique-name>.kdl`, that looks like this:
   ```kdl
   patch type="added" package="livekit-ffi" "Add support for foo"
   ```
   alternatively you may add the file to `./livekit-ffi/.nanpa/`, and then drop the `package="livekit-ffi"`.

   `type`s follow [Keep a Changelog](https://keepachangelog.com/en/1.1.0/#how). you may add multiple lines per file.
4. ilo will create an issue when there's changes in the main branch. use the checkboxes to pick which ones you want to bump. additionally, if you want to set a prerelease version on a package:
   > ilo prerelease rust-sdks/livekit-ffi alpha

   or to un-prerelease a package:
   > ilo prerelease rust-sdks/livekit-ffi
5. close the issue, and the workflow should run, making a new commit and tagging it with all changed package versions.

note that when updating a package and its dependent, you need to either bump them seperately, or manually update the dependency's Cargo.toml, and then edit the dependent's manifest to include the new dep version.

### repo settings that need to change

- add [ilo](https://github.com/apps/ilo-nanpa) to the repository
- set the `NANPA_WORKFLOW` environmental variable to `publish.yml`, for CI (not as a secret!)

### CODE REVIEW

**Comment by davidzhao** [comment]
> on PRs, for each change, add a file to .nanpa/<unique-name>.kdl, that looks like this:

It'd be great to have automation for this, otherwise it'd be easy for devs to forget.

**Review by davidzhao — APPROVED** [review]
lg!

**Comment by nbsp** [comment]
> > on PRs, for each change, add a file to .nanpa/.kdl, that looks like this:
> 
> It'd be great to have automation for this, otherwise it'd be easy for devs to forget.

i can always add this to the bot later (as a PR comment with a link), without any changes here

**Review by theomonnom — APPROVED** [review]
nice!

**Pull request merged**
